### ISSUE TITLE
Use thinned application from maven build

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/guide-spring-boot#138]
The project configuration already will thin the application during the `./mvnw package` command.  We can use a single stage `Dockerfile` to copy in the already thinned application and `lib.index.cache` like this:

```Dockerfile
# Build the image
FROM icr.io/appcafe/open-liberty:kernel-slim-java8-openj9-ubi

ARG VERSION=1.0
ARG REVISION=SNAPSHOT

LABEL \
  org.opencontainers.image.authors="Your Name" \
  org.opencontainers.image.vendor="Open Liberty" \
  org.opencontainers.image.url="local" \
  org.opencontainers.image.source="https://github.com/OpenLiberty/guide-spring-boot" \
  org.opencontainers.image.version="$VERSION" \
  org.opencontainers.image.revision="$REVISION" \
  vendor="Open Liberty" \
  name="hello app" \
  version="$VERSION-$REVISION" \
  summary="The hello application from the Spring Boot guide" \
  description="This image contains the hello application running with the Open Liberty runtime."

RUN cp /opt/ol/wlp/templates/servers/springBoot2/server.xml /config/server.xml

RUN features.sh

COPY --chown=1001:0 target/liberty/wlp/usr/shared/resources/lib.index.cache/ /lib.index.cache
COPY --chown=1001:0 target/liberty/wlp/usr/servers/defaultServer/apps/thin-guide-spring-boot-0.1.0.jar \
                    /config/dropins/spring/thin-guide-spring-boot-0.1.0.jar


RUN configure.sh 
```

I think this is a more simple `Dockerfile` than the two stage example that does the thinning in the `docker build`.

**Comment by tjwatson** [comment]
@cherylking FYI

**Comment by gkwan-ibm** [comment]
In the guide flow, the "Building and running the application in a Docker container" section does not have any configuration for LMP, that why the Dockerfile need to have 2 stages to build.

**Comment by tjwatson** [comment]
> In the guide flow, the "Building and running the application in a Docker container" section does not have any configuration for LMP, that why the Dockerfile need to have 2 stags to build.

I see, it is curious that the final `pom.xml` does have the plugin enabled.

**Comment by gkwan-ibm** [comment]
close
- no need to change
