### ISSUE TITLE
Running the application on Open Liberty - Skipping module guide-spring-boot which is not included

### ISSUE THREAD

**Issue by gusto2** [OpenLiberty/guide-spring-boot#157]
going throuh the step `Running the application on Open Liberty` 

Updated pom.xml and server.xml as in the tutorial
When running the step `./mvnw liberty:run` , the build is successful, but the applications doesn't run

```
[INFO] --- liberty-maven-plugin:3.10.2:run (default-cli) @ guide-spring-boot ---
[INFO] 
Skipping module guide-spring-boot which is not included in this invocation of the run goal.
```

I noticed the server.xml contains a file path which is not found in the build:
         location="thin-guide-spring-boot-0.1.0.jar"

**Comment by gkwan-ibm** [comment]
hi @gusto2 

Thank you to report this issue. 

Would you try the workaround by updating the pom.xml to change the liberty-maven-plugin version to 3.10 as following?

```
...
      <!-- Enable Liberty Maven plugin -->
      <plugin>
        <groupId>io.openliberty.tools</groupId>
        <artifactId>liberty-maven-plugin</artifactId>
        <version>3.10</version>
...
```

**Comment by gusto2** [comment]
looks ok, runnig the spring app on liberty
