### ISSUE TITLE
Link to springBootUtility reference at openliberty.io

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-spring-boot#21]
The guide currently links to the below:

https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_command_sbutility.html

It should eventually link to what is at openliberty.io.

@gkwan-ibm @lauracowen

**Comment by barecode** [comment]
Does that springBootUtility doc exist yet? I can't find it.

**Comment by lauracowen** [comment]
@barecode In OL docs? No

**Comment by barecode** [comment]
OK, so when that gets created in OL docs we can act on this issue.

**Comment by gkwan-ibm** [comment]
Pending on OL docs

**Comment by Rwalls1** [comment]
@gkwan-ibm @barecode OL doc has been published:
https://openliberty.io/docs/latest/reference/command/springbootUtility-thin.html
https://openliberty.io/docs/latest/reference/command/springbootUtility-help.html

**Comment by gkwan-ibm** [comment]
close
- the link was updated and it points to openliberty.io/docs
