### ISSUE TITLE
Having issues with 'Running the application on Open Liberty'

### ISSUE THREAD

**Issue by ThomFal** [OpenLiberty/guide-spring-boot#78]
Hi I just followed your guide and experienced some strange problems. When I try to access the Application on http://localhost:9080/hello it seems localhost refused the connections, but the server is running and the HelloControllerTest is running fine, too. I tried different ports or changing ports in the server.xml but nothing is fixxing the problem. I wondered if it could be something with the OSs firewall but then the docker container or java -jar .... approaches wouldn't work, too. right? 

To clarify things: I was under point 'Running the application on Open Liberty' and executed ./mvnw liberty:run inside the finish folder in a fresh repository. 
I'm running the whole app inside WSL2 on a Windows machine. If you need anything just let me know. 

Any help would be appreciated. Thanks in advance <3

**Comment by gkwan-ibm** [comment]
hi @ThomFal Thank you to report this issue. We'd like to reproduce your problem. Would you tell us the detail steps?

I tried the following without problem (except a warning. It does not break the app):
- `git clone https://github.com/openliberty/guide-spring-boot.git`
- `cd guide-spring-boot\finish`
- `mvnw package`
- `mvnw liberty:run`

**Comment by scottkurz** [comment]
Hi @ThomFal , does it help if you edit the `finish/src/main/liberty/config/server.xml` to add `host="*"` like:

```xml
  <httpEndpoint id="defaultHttpEndpoint"
                 host="*"
                  httpPort="9080"
                  httpsPort="9443" />
```

I wonder if crossing from WSL2 to your browser/client means this needs to be treated more like a remote host?

**Comment by ThomFal** [comment]
@scottkurz Yeah you're right with treating wsl like a remote host,  i didn't think of that. The host="*" parameter made it work!! Thanks a lot for your help guys!

**Comment by gkwan-ibm** [comment]
We will update the server.xml to include `host="*"`
