### ISSUE TITLE
How can I customize server.xml (src/main/liberty/config/server.xml not used)

### ISSUE THREAD

**Issue by uniquejava** [OpenLiberty/guide-spring-boot#93]
Looks like server.xml defined in `src/main/liberty/config/server.xml` not used.

For example, if I change the port number from 9080 to 8080, after docker image is built, the server is still running on 9080?

I look inside the container `/opt/ol/wlp/usr/servers/defaultServer/server.xml`, it's always the default server.xml copied from `/opt/ol/wlp/templates/servers/springBoot2/server.xml`, not the one I wanted.

**Comment by gkwan-ibm** [comment]
It is because the Dockerfile defines `RUN cp /opt/ol/wlp/templates/servers/springBoot2/server.xml /config/server.xml`.
You can change it to `COPY --chown=1001:0 src/main/liberty/config/server.xml /config/server.xml`.

We will study it further.

**Comment by gkwan-ibm** [comment]
For the guide flow, the server.xml is not created at the **Building and running the application in a Docker container** section, that why the Dockerfile copies server.xml from templates instead from the local `src` directory. Surely, you can update the server.xml and Dockerfile as your need.

**Comment by gkwan-ibm** [comment]
close
- see above comments
