### ISSUE TITLE
Update dependencies to the latest version

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-spring-boot#98]
Update dependencies used in the project for the guide to the latest when ready.

e.g. for [spring-boot-starter-parent](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-parent), move up to 2.6.2 when it's available.

**Comment by gkwan-ibm** [comment]
Based on https://spring.io/blog/2021/12/10/log4j2-vulnerability-and-spring-boot,  2.6.2 target is Dec 23, 2021

**Comment by gkwan-ibm** [comment]
close
- the guide was updated
